---

- name: disable ipv6 global
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  become: yes

- name: disable ipv6 as default
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  become: yes

- name: disable ipv6 on loop device
  ansible.posix.sysctl:
    name: net.ipv6.conf.lo.disable_ipv6
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  become: yes
