---

- name: adding domain name in hosts (ipv4)
  ansible.builtin.lineinfile:
    path: /etc/hosts
    insertafter: '^127\.0\.0\.1'
    line: '{{ extip }} {{ fqdn_name }} {{ hostname }}'
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: adding domain name to hostname file
  ansible.builtin.lineinfile:
    path: /etc/hostname
    regexp: '.'
    line: '{{ fqdn_name }}'
    owner: root
    group: root
    mode: '0644'
  become: yes
