---

- name: open port 80
  ansible.posix.firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled
  become: yes

- name: open port 443
  ansible.posix.firewalld:
    service: https
    permanent: yes
    immediate: yes
    state: enabled
  become: yes
