---

- name: creating user www-data for nginx
  ansible.builtin.user:
    name: www-data
    shell: /bin/bash
    uid: 1001
    create_home: false
  become: yes

- name: copy template config to remote-host
  ansible.builtin.template:
    src: templates/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: make backup of nginx-config
  ansible.builtin.copy:
    src: /etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf.bak
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: create folders for nxtc and certificates
  ansible.builtin.file:
    path: "{{ cm_pathlist }}"
    owner: www-data
    group: www-data
    mode: '0751'
    state: directory
  become: yes
  loop: "{{ custom_pathlist }}"
  loop_control:
    loop_var: cm_pathlist
