---

- name: enable autostart for nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: stopped
  become: yes

- name: creating user www-data for nginx
  ansible.builtin.user:
    name: www-data
    shell: /bin/bash
    uid: 1001
    

- name: make backup of nginx-config
  ansible.builtin.copy:
    src: /etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf.bak
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: copy template config to remote-host
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  become: yes

